[package]
name = "fft-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0"
gdal = "0.18"
ndarray = "0.15"
ndarray-linalg = "0.16"
num-complex = "0.4"
rayon = "1.10"
rustfft = "6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nalgebra = "0.32"
once_cell = "1.19.0"
dashmap = "6.1.0"
console = "0.16.2"

[dev-dependencies]
approx = "0.5.1"
