[package]
name = "fft-analyze"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
ndarray = "0.15"
rayon = "1.10"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
gdal = "0.18"
serde_json = "1.0"
fft-core = { path = "../fft-core" }
charming = "0.6"
console = "0.16.2"

[dev-dependencies]
approx = "0.5.1"
assert_cmd = "2.1.2"
csv = "1.3"
gdal = "0.18"
predicates = "3.1.3"
serde_json = "1.0"
tempfile = "3.24.0"
