[package]
name = "fft-process"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

anyhow = "1.0"

clap = { version = "4.5", features = ["derive"] }

fft-core = { path = "../fft-core" }

ndarray = "0.15"

rayon = "1.10"

tracing = "0.1"
gdal = "0.18"
console = "0.16.2"

[dev-dependencies]
assert_cmd = "2.1.2"
gdal = "0.18"
predicates = "3.1.3"
serde_json = "1.0.149"
tempfile = "3.24.0"
