[package]
name = "fft-inverse"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
fft-core = { path = "../fft-core" }
rustfft = "6.1"
ndarray = "0.15"
gdal = "0.18"
serde_json = "1.0"
rayon = "1.10"
walkdir = "2.5"
num-complex = "0.4"
console = "0.16.2"

[dev-dependencies]
approx = "0.5.1"
assert_cmd = "2.1.2"
gdal = "0.18"
predicates = "3.1.3"
serde_json = "1.0"
tempfile = "3.24.0"
